"""initial_calculation_history

Revision ID: c1d442fc8364
Revises: 
Create Date: 2026-05-08 14:17:12.909631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d442fc8364'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calc_type', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('ovz', sa.Float(), nullable=True),
    sa.Column('vz', sa.Float(), nullable=True),
    sa.Column('pension_amount', sa.Float(), nullable=True),
    sa.Column('insurance_years', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_history_calc_type'), 'calculation_history', ['calc_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculation_history_calc_type'), table_name='calculation_history')
    op.drop_table('calculation_history')
    # ### end Alembic commands ###
